name: 'Use S3cmd'
description: 'Use S3cmd cli to interact with s3 object storage.'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  provider:
    description: 'config provider to make it easier to use the cli as action'
    default: 'linode'
  region:
    description: 's3 region'
  access_key: 
    description: 's3 access key'
    required: true
  secret_key: 
    description: 's3 secret key'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
